# Image Segmentation (Face Detection) using Deep Learning

In [5]:
import tensorflow as tf
from PIL import Image
import numpy as np

filename_queue = tf.train.string_input_producer(['data/neg_1.png']) #  list of files to read

reader = tf.WholeFileReader()
key, value = reader.read(filename_queue)

im = tf.image.decode_png(value, channels = 3) # use png or jpg decoder based on your files.
im_res = tf.image.resize_images(im, [300,300])
print(im_res)
ip = tf.expand_dims(im_res, 0)
kernel = tf.cast(tf.constant([[[[1,1,1],[1,1,1],[1,1,1]],[[1,1,1],[1,1,1],[1,1,1]],[[1,1,1],[1,1,1],[1,1,1]]]]), tf.float32)
#kernel = np.array([[[[1, 1,1], [1, 1,1]],[[1, 1,1], [1, 1,1]], [[1, 1,1], [1, 1,1]]]])


conv1 = tf.nn.conv2d(ip, kernel, strides=[1, 1,1,1], padding='SAME')
relu1 = tf.nn.relu(conv1)
init_op = tf.initialize_all_variables()
with tf.Session() as sess:
    sess.run(init_op)

  # Start populating the filename queue.

    coord = tf.train.Coordinator()
    threads = tf.train.start_queue_runners(coord=coord)

    for i in range(1): #length of your filename list
        image = im.eval() #here is your image Tensor :) 

    print(image.shape)
    Image.fromarray(np.asarray(image)).show()

    coord.request_stop()
    coord.join(threads)
    print(sess.run(conv1))
    print(sess.run(relu1))


Tensor("Squeeze_4:0", shape=(300, 300, 3), dtype=float32)
Instructions for updating:
Use `tf.global_variables_initializer` instead.
(348, 348, 3)
[[[[  841.2800293    841.2800293    841.2800293 ]
   [ 1290.          1290.          1290.        ]
   [ 1337.51989746  1337.51989746  1337.51989746]
   ..., 
   [  462.59994507   462.59994507   462.59994507]
   [  461.03997803   461.03997803   461.03997803]
   [  307.48001099   307.48001099   307.48001099]]

  [[  868.30883789   868.30883789   868.30883789]
   [ 1306.17602539  1306.17602539  1306.17602539]
   [ 1320.31188965  1320.31188965  1320.31188965]
   ..., 
   [  471.59515381   471.59515381   471.59515381]
   [  470.80316162   470.80316162   470.80316162]
   [  312.7840271    312.7840271    312.7840271 ]]

  [[  854.23193359   854.23193359   854.23193359]
   [ 1297.67041016  1297.67041016  1297.67041016]
   [ 1318.60791016  1318.60791016  1318.60791016]
   ..., 
   [  492.78240967   492.78240967   492.78240967]
   [  495.2975769    49

# Caution! Rough Work Below

In [25]:
import tensorflow as tf
import numpy as np
file_name = tf.constant('hot.png')
im = tf.image.decode_png(file_name, channels=3)
print(im)
im_res = tf.image.resize_images(im, [300,300])
print(im_res)
ip = tf.expand_dims(im_res, 0)
kernel = tf.cast(tf.constant([[[[1,1,1],[1,1,1],[1,1,1]],[[1,1,1],[1,1,1],[1,1,1]],[[1,1,1],[1,1,1],[1,1,1]]]]), tf.float32)
#kernel = np.array([[[[1, 1,1], [1, 1,1]],[[1, 1,1], [1, 1,1]], [[1, 1,1], [1, 1,1]]]])


conv1 = tf.nn.conv2d(ip, kernel, strides=[1, 1,1,1], padding='SAME')

with tf.Session() as sess:
    print(sess.run(im))
    #print(sess.run(conv1))

Tensor("DecodePng:0", shape=(?, ?, 3), dtype=uint8)
Tensor("Squeeze_23:0", shape=(300, 300, 3), dtype=float32)


InvalidArgumentError: Invalid PNG header, data size 7
	 [[Node: DecodePng = DecodePng[channels=3, dtype=DT_UINT8, _device="/job:localhost/replica:0/task:0/cpu:0"](Const_29)]]

Caused by op 'DecodePng', defined at:
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-25-095937267c5f>", line 4, in <module>
    im = tf.image.decode_png(file_name, channels=3)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_image_ops.py", line 379, in decode_png
    channels=channels, dtype=dtype, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Invalid PNG header, data size 7
	 [[Node: DecodePng = DecodePng[channels=3, dtype=DT_UINT8, _device="/job:localhost/replica:0/task:0/cpu:0"](Const_29)]]


In [26]:
import tensorflow as tf
import numpy as np
from scipy import misc # feel free to use another image loader
from glob import glob

file_names = glob('data/*.jpg')

def create_batches(batch_size, list_of_images):
    images = []
    for img in list_of_images:
        images.append(misc.imread(img))
        images = np.asarray(images)

    while (True):
        for i in range(0,total,batch_size):
            yield(images[i:i+batch],labels[i:i+batch])
            
create_batches(3, file_names)

imgs = tf.placeholder(tf.float32,shape=[None,height,width,colors])
lbls = tf.placeholder(tf.int32, shape=[None,label_dimension])

with tf.Session() as sess:
#define rest of graph here
# convolutions or linear layers and cost function etc.


    batch_generator = create_batches(batch_size)
    for i in range(number_of_epochs):
        images, labels = batch_generator.next()
        loss_value = sess.run([loss], feed_dict={imgs:images, lbls:labels})

NameError: name 'height' is not defined

In [23]:
data_dir = './data'
image_size = [300, 300]


print(file_names)

image_orig = tf.image.decode_jpeg('image.jpg', channels=3)
image_res = tf.image.resize_images(image_orig, image_size)
data_set = tf.stack([image_res])

with tf.Session() as sess:
    print(sess.run(data_set))

['./data/gray_kitten.jpg', './data/image.jpg', './data/image2.jpg']


InvalidArgumentError: Invalid JPEG data, size 9
	 [[Node: DecodeJpeg_20 = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](DecodeJpeg_20/contents)]]

Caused by op 'DecodeJpeg_20', defined at:
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-23-10f5f74740b1>", line 7, in <module>
    image_orig = tf.image.decode_jpeg('image.jpg', channels=3)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_image_ops.py", line 345, in decode_jpeg
    dct_method=dct_method, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Invalid JPEG data, size 9
	 [[Node: DecodeJpeg_20 = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](DecodeJpeg_20/contents)]]


In [17]:
print(tf.__version__)

1.0.1


# Rough Work Ends Here!